/**:
  ros__parameters:
    cluster_max_size: 1000
    cluster_min_size: 132
    cluster_tol: 0.02
    plane_dist_thresh: 0.005
    plane_max_iter: 50
    ror_min_neighbors: 15
    ror_radius_search: 0.005
    voxel_leaf_size: 0.002
    x_filter_max: 0.19999999999999996
    x_filter_min: -0.2
    y_filter_max: 0.19999999999999996
    y_filter_min: -0.2
    z_filter_max: 0.25
    z_filter_min: 0.05
